export const REQUEST_BUSINESSES = "REQUEST_BUSINESSES";
export const GET_BUSINESSES_FAILURE = "GET_BUSINESSES_FAILURE";
export const GET_BUSINESSES_SUCCESS = "GET_BUSINESSES_SUCCESS";

export const TOGGLE_NEW_BUSINESS_FORM = "TOGGLE_NEW_BUSINESS_FORM";
export const TOGGLE_EDIT_BUSINESS_FORM = "TOGGLE_EDIT_BUSINESS_FORM";
export const SELECT_BUSINESS = "SELECT_BUSINESS"
export const DELETE_BUSINESS = "DELETE_BUSINESS"